name: smart_city_garbage_collection_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.3
  mobile_scanner: ^5.1.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  confetti: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/images/
